### PR TITLE
fix: prevent 'invalid Uri' error

### LINKED ISSUE #688: LdpPresentationGenerator can cause an "Invalid Uri" error
# Bug Report

## Describe the Bug

The LdpPresentationGenerator can run into an “Invalid Uri” error if the keyId is specified incorrectly during registration. This is not the case with the JwtPresentationGenerator.

Not sure if this is a bug, as it should work if only the key is entered as keyId, without the controller. But there is an inconsistency between the Jwt and the LdpPresentationGenerator which in my case lead to a error.

### Expected Behavior

_A clear and concise description of what you expected to happen._

### Observed Behavior

While the LdpPresenationController runs into the error “Invalid Uri” if the keyId is specified together with the controller, it works with the JwtPresenationController.

## Steps to Reproduce

1. Activate/register the participant with keyId as controller + keyId
2. Verify this participant with an ldp-credential

## Context Information

_Add any other context about the problem here._

## Detailed Description

If the keyId is not defined as only key, e.g. key-1 when registering/activating a participant, but as controller + key, e.g. did:web:test#key-1, then this leads to an error in LdpPresentationGenerator in signPresentation: https://github.com/eclipse-edc/IdentityHub/blob/9ad917f47476a0fd5f829f3f3f06681aff24d868/core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGenerator.java#L172

The JwtPresentationGenerator checks whether the controller is already contained in the keyId:
https://github.com/eclipse-edc/IdentityHub/blob/9ad917f47476a0fd5f829f3f3f06681aff24d868/core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/JwtPresentationGenerator.java#L97

## Possible Implementation

An If-statement in the LdpPresentationGenerator to check if the controller is already included in the keyId, as in the JwtPresentationGenerator.

### PR DESCRIPTION
**Pull request by u-veys**
## What this PR changes/adds

Add an if-statement to check whether the keyId already contains the controller. If not, the publicKeyId is extended by controller + # publicKeyId.

## Why it does that

If the controller is already included in the publicKeyId, and a uri is still created together with the controller and publicKeyId, an “invalid Uri” error occurs.

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Who will sponsor this feature?

_Please @-mention the committer that will sponsor your feature_.

## Linked Issue(s)

Closes #688

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
please add a test for this.

File: core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGenerator.java [hunk 1]
```diff
@@ -159,6 +159,10 @@ private JsonArray toJsonArray(List<VerifiableCredentialContainer> credentials) {
     }
 
     private JsonObject signPresentation(JsonObject presentationObject, SignatureSuite suite, String suiteIdentifier, PrivateKey pk, String publicKeyId, String controller) {
+        if (!publicKeyId.startsWith(controller)) {
```
Comment (paullatzelsperger) [inline core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGenerator.java:162]: please do not re-use and mutate input arguments. instead, assign a new variable inside the method. For reference, look at `JwtPresentationGenerator`.

**Review by paullatzelsperger — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
@u-veys we have another PR that must get merged first, otherwise the tests here will fail. Once #702 is merged, pls rebase your pr

**Comment by u-veys** [comment]
@paullatzelsperger Unfortunately I'm not quite familiar with github yet, soI wanted to ask what exactly is meant by rebase PR? In the commits above I used the “update branch” function of Github, which automatically made a merge to synchronize my fork. By rebase PR, do you mean a git rebase to sync the fork?

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger Unfortunately I'm not quite familiar with github yet, soI wanted to ask what exactly is meant by rebase PR? In the commits above I used the “update branch” function of Github, which automatically made a merge to synchronize my fork. By rebase PR, do you mean a git rebase to sync the fork?

it means that your feature branch, on which the PR is based, needs to incorporate the latest changes from `main`. I usually do it like this:
```shell
git checkout your_feature_branch
git fetch origin main:main
git rebase main
```
resolve conflicts if there are any, then:
```shell
git push --force
```
