### PR TITLE
fix: add missing sql dependency to bom and remove not null constraint

### LINKED ISSUE #709: not-null constraint violation on "raw_vc" column of "credential_resource" table
# Bug Report

## Describe the Bug

When I try to issue credentials using sql persistence I get:
```
org.postgresql.util.PSQLException: ERROR: null value in column "raw_vc" of relation "credential_resource" violates not-null constraint
  Detail: Failing row contains (a10186fc-cfca-4d67-af65-207b48de532a, 1744807925775, did:web:localhost%3A56512:issuer, did:web:localhost%3A16417:user1, 500, {}, null, null, null, 3, {"credentialSubject":[{"id":"did:web:localhost%3A16417:user1","n..., issuer).
```

### Expected Behavior

No exception, correct issuance

### Observed Behavior

A null is passed here:
https://github.com/eclipse-edc/IdentityHub/blob/ca3e2a8f4d5f27afc053a74718642e595b9e624b/core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImpl.java#L150

## Steps to Reproduce

add `api(project(":extensions:store:sql:identity-hub-credentials-store-sql"))` to the `issuerservice-feature-sql-bom` and run `DcpIssuanceFlowEndToEndTest`

## Context Information

main branch

## Possible Implementation

add `api(project(":extensions:store:sql:identity-hub-credentials-store-sql"))` to the `issuerservice-feature-sql-bom`, replace `null` in the `IssuanceProcessManagerImpl` with `credential.getRawVc()

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Removes `NOT NULL` constraint on raw_vc column in sql credential store.
Adds `identity-hub-credentials-store-sql` to the sql-bom so the flow can be covered by the `DcpIssuanceFlowEndToEndTest`, that was still failing.

To fix it I had to add a patch in the `BitstringStatusListManager`, because otherwise the `published=true` information gets lost.
That does the job but in a really ugly and not optimal way, so my proposal would be:

Remove persistance from the `StatusListCredentialPublisher` implementation, because, as the interface is stating, that component should just publish and report the result of the publication, and the persistence could be made by the caller (the `BitstringStatusListManager`) directly, so in the `.compose` block after calling the publisher the `published` flag could be directly added to the metadata together with the `publicUrl` one.

@wolf4ood @paullatzelsperger let me know what you think about, I can take care to do this change directly

NOTE: unit tests are broken but I'd prefer to have some discussion about the solution to adopt before going and fixing them

## Why it does that

_Briefly state why the change was necessary._

## Further notes

- removed `canHandle` and `unpublish` methods from the `StatusListCredentialPublisher` as they are not used yet and it's still not clear how they'll be used, to be reintroduced back when needed with the proper signature

## Who will sponsor this feature?

_Please @-mention the committer that will sponsor your feature_.

## Linked Issue(s)

Closes #709 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

**Comment by wolf4ood** [comment]
Hi @ndr-brt 

Just a quick note, the rawVc was intentionally set to null, since the issuer should not store the signed VC in the database.
The fix should take into account that  rawVc must be null for the issuer cred store but not for the identityHub one.

**Comment by ndr-brt** [comment]
> Hi @ndr-brt
> 
> Just a quick note, the rawVc was intentionally set to null, since the issuer should not store the signed VC in the database. The fix should take into account that rawVc must be null for the issuer cred store but not for the identityHub one.

In fact I discovered that I'm not fixing the bug that I reported but a different one! :smiling_face_with_tear:

File: core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java [hunk 1]
```diff
@@ -179,16 +177,16 @@ private VerifiableCredentialResource createCredentialResource(String participant
...
-            meta.put(PUBLIC_URL, url);
-            var updated = statusListCredential.toBuilder().metadata(meta).build();
-            var storeResult = upsert(updated);
-            return storeResult.succeeded() ?
-                    Result.success(updated) : Result.failure(storeResult.getFailureDetail());
-        });
+        return publisher.publish(statusListCredential)
+                .compose(url -> {
+                    var meta = new HashMap<>(statusListCredential.getMetadata());
+                    meta.put("published", true);
```
Comment (paullatzelsperger) [inline core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java:183]: I'd prefer to set the `"published"` entry in the metadata map directly in the `LocalCredentialPublisher`

Comment (ndr-brt) [reply core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java:183]: I think we should try to isolate changes to the metadata in a single place, and the looks to be the best place to do, doing that in the publisher would be a sort of unexpected side effect, the publisher is just expected to publish, then if the publish goes through, the manager will update metadata, status and what's needed.

plus, if we're considering the possibility of different publisher implementations, doing that in the caller makes even more sense.

Comment (paullatzelsperger) [reply core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java:183]: similarly, we'd have to re-implement this entire behavior for status list implementations other than BitStringStatusList, e.g. StatusList2021, which is definitely planned.

I'd say the chances of ever implementing an addition publisher are magnitudes lower than additional status list impls. By that logic, I'd probably even move both the public url and the "published" flag into the publisher, because that were it semantically belongs.

Comment (ndr-brt) [reply core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java:183]: this is a design issue, in fact the way the different status list kinds are managed should be the same and only the implementation specific behavior should finish into a specification, so describing it following the  abstraction pattern (that's not the best way to go but the easy to explain the concept in this moment) there would be an abstract `StatusListManager` that contains this common logic that:
- calls the provider
- updates the metadata

then the two extensions `BitStringStatusListManager` and `StatusList2021Manager` will contain the related custom logic.

Comment (paullatzelsperger) [reply core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java:183]: yep, that sounds reasonable. such a refactoring could be done in a subsequent PR, or in this, either way is fine with me.

Comment (ndr-brt) [reply core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java:183]: It could be done when the `StatusList2021` implementation will be done, I wouldn't put additional pressure on this bugfix PR

File: spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListCredentialPublisher.java [hunk 2]
```diff
@@ -25,34 +26,10 @@ public interface StatusListCredentialPublisher {
...
-     * <ul>
-     *     <li>invalid format: the credential is in a format that the publisher can't handle (e.g. binary data)</li>
-     *     <li>invalid type: the credential is not a status list credential</li>
-     * </ul>
-     *
-     * @param participantContextId   The ID of the participant context that represents the issuer
-     * @param statusListCredentialId The ID of the {@link org.eclipse.edc.identityhub.spi.verifiablecredentials.model.VerifiableCredentialResource} that contains the status list credential.
-     * @return true if can be handled, false otherwise. This does not necessarily mean, that the credential can be <em>published</em> as well.
-     */
-    boolean canHandle(String participantContextId, String statusListCredentialId);
```
Comment (paullatzelsperger) [inline spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListCredentialPublisher.java:47]: why were these two methods removed?

Comment (ndr-brt) [reply spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListCredentialPublisher.java:47]: specified in "further notes":
> removed canHandle and unpublish methods from the StatusListCredentialPublisher as they are not used yet and it's still not clear how they'll be used, to be reintroduced back when needed with the proper signature

**Review by paullatzelsperger — APPROVED** [review]
