### PR TITLE
fix: use mapper embedding date-time in LocalStatusListCredentialPublisherExtension

### LINKED ISSUE #710: use `ObjectMapper` embedding date/time modules in `LocalStatusListCredentialPublisherExtension`
# Bug Report

## Describe the Bug

In `LocalStatusListCredentialPublisherExtension`, conversion from jwt to `VerifiableCredential` fails because provided Mapper does not include the date/time modules:

```bash
[2025-04-16 13:33:35] [SEVERE ] JerseyExtension: Unexpected exception caught
││ org.eclipse.edc.spi.EdcException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type
`java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: org.eclipse.edc.iam.verifiablecred ││     at org.eclipse.edc.issuerservice.publisher.api.StatusListCredentialController.resolveStatusListCredential(StatusListCredentialController.java:95)                                                                                                                                                                    ││     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
```

### Expected Behavior

Provided mapper should include data/time module, and thus conversion should work.

### Observed Behavior

Mapping from jwt to VC fails
 
## Context Information

_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

### PR DESCRIPTION
**Pull request by bscholtes1A**
## What this PR changes/adds

Use mapper including date/time modules in `LocalStatusListCredentialPublisherExtension`.

## Why it does that

Fix error during mapping to VC.

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Who will sponsor this feature?

@bscholtes1A 

## Linked Issue(s)

Closes #710 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java [hunk 1]
```diff
@@ -63,7 +69,7 @@ public String name() {
     public void initialize(ServiceExtensionContext context) {
         portMappingRegistry.register(new PortMapping(STATUS_LIST, config.port(), config.path()));
 
-        webServer.registerResource(STATUS_LIST, new StatusListCredentialController(store, context.getMonitor(), new ObjectMapper()));
+        webServer.registerResource(STATUS_LIST, new StatusListCredentialController(store, monitor, JacksonJsonLd.createObjectMapper()));
```
Comment (paullatzelsperger) [inline extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java:72]: the object mapper should not be "hard-coded", better to use:
```java
@Inject 
private TypeManager typeManager;

public void initialize(ServiceExtensionContext context){
  //...
  var objectMapper = typeManager.getMapper(JSON_LD);
  //...
}
```

**Review by paullatzelsperger — APPROVED** [review]

File: extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java [hunk 2]
```diff
@@ -61,9 +72,10 @@ public String name() {
 
     @Override
     public void initialize(ServiceExtensionContext context) {
+        var objectMapper = typeManager.getMapper(JSON_LD);
         portMappingRegistry.register(new PortMapping(STATUS_LIST, config.port(), config.path()));
 
-        webServer.registerResource(STATUS_LIST, new StatusListCredentialController(store, context.getMonitor(), new ObjectMapper()));
+        webServer.registerResource(STATUS_LIST, new StatusListCredentialController(store, monitor, objectMapper));
```
Comment (wolf4ood) [inline extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java:78]: I think it's better to pass or a `Supplier<ObjectMapper>` or the type manager and the and the `JSON_LD` key to the `StatusListCredentialController`. We had strange behavior in the past where the `JSON_LD`  was not registered yet in the `TypeManager` and the get returned the default one, which probably it's not the expected one

**Review by wolf4ood — APPROVED** [review]
