### PR TITLE
fix: set keypair to ACTIVE

### LINKED ISSUE #284: Set state to `ACTIVE` when creating new key pairs
# Bug Report

## Describe the Bug

When new key pairs are created via the Management API, their state is set to `CREATED`, but never advances to `ACTIVE`.

## Possible Implementation

- When creating a participant, the key pair that was created alongside them should be set to `ACTIVE`. 
- The `KeyPairDescriptor` gets a new field `isActive`, which determines whether a key pair is set to `ACTIVE` or `CREATED`. defaults to `true`
- When a new key pair is created, and the `isActive` flag is `false`, and the participant does not have an active keypair, a warning is logged
- The key pair management API gets a new method `POST "/v1/participants/{participantId}/keypairs/{keyPairId}/activate"` that allows a state change `CREATED -> ACTIVE`, and returns a 400 in all other cases.

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

This PR fixes the handling of the KeyPairResource's ACTIVE state

## Why it does that

There was no way to move the key pair to the ACTIVE state before.

## Linked Issue(s)

Closes #284

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApi.java [hunk 1]
```diff
@@ -82,6 +82,22 @@ public interface KeyPairResourceApi {
     )
     void addKeyPair(String participantId, KeyDescriptor keyDescriptor, boolean makeDefault, SecurityContext securityContext);
 
+
+    @Tag(name = "KeyPairResources Management API")
+    @Operation(description = "Sets a KeyPairResource to the ACTIVE state. Will fail if the current state is anything other than ACTIVE or CREATED.",
+            responses = {
```
Comment (bscholtes1A) [inline extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApi.java:88]: Could you please add the `participantId` path param for this new API ? See here: https://github.com/eclipse-edc/IdentityHub/pull/285/files

**Review by bscholtes1A — CHANGES_REQUESTED** [review]

**Review by bscholtes1A — APPROVED** [review]

**Review by bscholtes1A — APPROVED** [review]
